### ISSUE TITLE
NameError: name 'token_data' is not defined

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/aiopogo#2]
[2017-02-06 14:19:22,720][   ERROR][worker-6] A wild exception appeared!
Traceback (most recent call last):
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/pgoapi.py", line 179, in call
    response = await request.request(self._api_endpoint, self._req_method_list, self._position)
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/rpc_api.py", line 164, in request
    raise AuthTokenExpiredException
pogo_async.exceptions.AuthTokenExpiredException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/develop/productiv/monocle/worker.py", line 777, in visit
    return await self.visit_point(point, bootstrap=bootstrap)
  File "/home/develop/productiv/monocle/worker.py", line 884, in visit_point
    responses = await self.call(request)
  File "/home/develop/productiv/monocle/worker.py", line 646, in call
    response = await request.call()
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/pgoapi.py", line 186, in call
    await self._auth_provider.get_access_token(force_refresh=True)
  File "/home/develop/lib64/python3.5/site-packages/pogo_async/auth_ptc.py", line 192, in get_access_token
    expires = int(token_data.get('expires', [0])[0]) - 3600
NameError: name 'token_data' is not defined

**Comment by evenly-epic-mule** [comment]
should be fixed with https://github.com/Noctem/pgoapi/commit/96c613c14174e1aff7d18b621b8602b75d6f2c0f
