### ISSUE TITLE
KeyError resp.ParseFromString(plat_response['response'])

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/aiopogo#3]
```
[2017-03-01 08:44:23][   ERROR][worker-73] A wild KeyError appeared!
Traceback (most recent call last):
  File "/home/develop/productiv/monocle/worker.py", line 644, in visit
    await self.login()
  File "/home/develop/productiv/monocle/worker.py", line 210, in login
    await self.app_simulation_login(version)
  File "/home/develop/productiv/monocle/worker.py", line 290, in app_simulation_login
    tutorial_state = await self.get_player()
  File "/home/develop/productiv/monocle/worker.py", line 222, in get_player
    responses = await self.call(request, chain=False)
  File "/home/develop/productiv/monocle/worker.py", line 491, in call
    response = await request.call()
  File "/home/develop/lib64/python3.5/site-packages/aiopogo/pgoapi.py", line 149, in call
    response = await request.request(self._api_endpoint, self._req_method_list, self._position)
  File "/home/develop/lib64/python3.5/site-packages/aiopogo/rpc_api.py", line 126, in request
    response_dict = self._parse_main_response(response, subrequests)
  File "/home/develop/lib64/python3.5/site-packages/aiopogo/rpc_api.py", line 367, in _parse_main_response
    resp.ParseFromString(plat_response['response'])
KeyError: 'response'
```

**Comment by Noctem** [comment]
Fixed in 11f575331bd921fb85c06f9c1a9bb1472d2ecd18.
